services:
  db:
    image: "postgres:16"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ukio_code_test
      - POSTGRES_PASSWORD=ukio_code_test
      - POSTGRES_DB=ukio_code_test
